import 'dotenv/config';
import { db } from './client';
import { products } from './schema/products';
import { categories } from './schema/products';
import { sql } from 'drizzle-orm';

async function seed() {
  console.log('🌱 Starting seed...');

  // Clear existing data
  await db.delete(products);
  
  console.log('Creating categories...');
  
  // Create categories
  const categoryData = [
    { name: 'Semillas', slug: 'semillas', description: 'Semillas de alta germinación' },
    { name: 'Tierra', slug: 'tierra', description: 'Tierra preparada para jardín' },
    { name: 'Composta', slug: 'composta', description: 'Composta orgánica premium' },
    { name: 'Accesorios', slug: 'accesorios', description: 'Herramientas y accesorios' },
  ];

  for (const cat of categoryData) {
    await db.execute(sql`INSERT INTO categories (name, slug, description) VALUES (${cat.name}, ${cat.slug}, ${cat.description}) ON CONFLICT (slug) DO NOTHING`);
  }

  console.log('Creating products...');

  // Seed products - Semillas
  const seedProducts = [
    // SEMILLAS - Hortalizas
    {
      name: 'Tomate Cherry',
      slug: 'tomate-cherry',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Tomate cherry de alta producción, ideal para climas cálidos. Produce frutos pequeños y dulces durante todo el ciclo. Excelente para balcones y huertos urbanos.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'seca_calida', 'templada'],
      sowMonths: [1, 2, 3, 8, 9, 10],
      harvestMonths: [4, 5, 6, 11, 12],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'maceta_grande',
      germinationRate: 92,
      daysToGerminate: 7,
      daysToHarvest: 75,
      weightOptions: [
        { g: 50, price: 35, stock: 100 },
        { g: 250, price: 120, stock: 50 },
      ],
      images: ['https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=400'],
      price: 35,
      stock: 150,
      seoTitle: 'Semillas de Tomate Cherry Orgánico | Jardín Verde',
      seoDescription: 'Compra semillas de tomate cherry con 92% de germinación. Ideal para clima de Colima. Envío a toda México.',
    },
    {
      name: 'Chile Serrano',
      slug: 'chile-serrano',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Chile serrano típico mexicano, perfecto para salsas y guisos. Planta vigorosa y productiva.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'seca_calida'],
      sowMonths: [2, 3, 4],
      harvestMonths: [5, 6, 7, 8],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'maceta_grande',
      germinationRate: 88,
      daysToGerminate: 14,
      daysToHarvest: 90,
      weightOptions: [
        { g: 30, price: 28, stock: 80 },
        { g: 100, price: 75, stock: 40 },
      ],
      images: ['https://images.unsplash.com/photo-1583119022894-919a4cc2c21c?w=400'],
      price: 28,
      stock: 120,
      seoTitle: 'Semillas de Chile Serrano Orgánico',
      seoDescription: 'Semillas de chile serrano para clima cálido. Alta germinación.',
    },
    {
      name: 'Jitomate Saladette',
      slug: 'jitomate-saladette',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Jitomate saladette ideal para frescos y cocina. Producción abundante.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [1, 2, 8, 9],
      harvestMonths: [4, 5, 11, 12],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'jardín',
      germinationRate: 90,
      daysToGerminate: 8,
      daysToHarvest: 85,
      weightOptions: [
        { g: 50, price: 32, stock: 90 },
        { g: 250, price: 110, stock: 45 },
      ],
      images: ['https://images.unsplash.com/photo-1546470427-227c7b3f8311?w=400'],
      price: 32,
      stock: 135,
      seoTitle: 'Semillas de Jitomate Saladette',
      seoDescription: 'Calidad profesional para tu huerto.',
    },
    {
      name: 'Pepino',
      slug: 'pepino',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Pepino crujiente y refrescante. Ideal para clima cálido y húmedo.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [2, 3, 4, 8, 9],
      harvestMonths: [5, 6, 7, 10, 11],
      waterNeeds: 3,
      sunNeeds: 2,
      careLevel: 1,
      spaceNeeded: 'jardín',
      germinationRate: 95,
      daysToGerminate: 6,
      daysToHarvest: 60,
      weightOptions: [
        { g: 100, price: 45, stock: 70 },
        { g: 500, price: 180, stock: 30 },
      ],
      images: ['https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400'],
      price: 45,
      stock: 100,
      seoTitle: 'Semillas de Pepino Orgánico',
      seoDescription: 'Alta germinación, ideal para Colima.',
    },
    {
      name: 'Calabaza',
      slug: 'calabaza',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Calabaza tradicional mexicana, versátil en la cocina.',
      isOrganic: false,
      climateZones: ['costera_humeda', 'seca_calida', 'templada'],
      sowMonths: [3, 4, 5],
      harvestMonths: [7, 8, 9],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'campo',
      germinationRate: 94,
      daysToGerminate: 7,
      daysToHarvest: 100,
      weightOptions: [
        { g: 100, price: 38, stock: 60 },
        { g: 500, price: 150, stock: 25 },
      ],
      images: ['https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=400'],
      price: 38,
      stock: 85,
    },
    {
      name: 'Frijol Negro',
      slug: 'frijol-negro',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Frijol negro típico mexicano, alto rendimiento.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [6, 7, 8],
      harvestMonths: [10, 11],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'jardín',
      germinationRate: 93,
      daysToGerminate: 8,
      daysToHarvest: 110,
      weightOptions: [
        { g: 250, price: 55, stock: 55 },
        { g: 1000, price: 180, stock: 20 },
      ],
      images: ['https://images.unsplash.com/photo-1584736286279-4a865523c3ce?w=400'],
      price: 55,
      stock: 75,
    },
    {
      name: 'Ejote',
      slug: 'ejote',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Ejote tierno y delicioso, fácil de cultivar.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [2, 3, 4, 8, 9],
      harvestMonths: [5, 6, 10, 11],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'jardín',
      germinationRate: 91,
      daysToGerminate: 7,
      daysToHarvest: 65,
      weightOptions: [
        { g: 100, price: 40, stock: 65 },
      ],
      images: ['https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400'],
      price: 40,
      stock: 65,
    },
    {
      name: 'Cebolla Blanca',
      slug: 'cebolla-blanca',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Cebolla blanca paraTodo uso, almacenamiento prolongado.',
      isOrganic: false,
      climateZones: ['templada', 'fria_montana'],
      sowMonths: [9, 10, 11],
      harvestMonths: [3, 4, 5],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'maceta_grande',
      germinationRate: 85,
      daysToGerminate: 10,
      daysToHarvest: 150,
      weightOptions: [
        { g: 50, price: 30, stock: 80 },
        { g: 250, price: 95, stock: 35 },
      ],
      images: ['https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400'],
      price: 30,
      stock: 115,
    },
    {
      name: 'Ajo',
      slug: 'ajo',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Ajo criollo mexicano, sabor intenso.',
      isOrganic: true,
      climateZones: ['templada', 'fria_montana'],
      sowMonths: [10, 11, 12],
      harvestMonths: [4, 5],
      waterNeeds: 1,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'maceta_grande',
      germinationRate: 88,
      daysToGerminate: 14,
      daysToHarvest: 180,
      weightOptions: [
        { g: 100, price: 48, stock: 50 },
        { g: 500, price: 200, stock: 15 },
      ],
      images: ['https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?w=400'],
      price: 48,
      stock: 65,
    },
    {
      name: 'Lechuga Romana',
      slug: 'lechuga-romana',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Lechuga romana crujiente, ideal para ensaladas frescas.',
      isOrganic: true,
      climateZones: ['templada', 'fria_montana'],
      sowMonths: [1, 2, 9, 10, 11],
      harvestMonths: [3, 4, 11, 12],
      waterNeeds: 2,
      sunNeeds: 2,
      careLevel: 1,
      spaceNeeded: 'maceta_pequeña',
      germinationRate: 90,
      daysToGerminate: 6,
      daysToHarvest: 70,
      weightOptions: [
        { g: 30, price: 25, stock: 90 },
        { g: 100, price: 65, stock: 40 },
      ],
      images: ['https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400'],
      price: 25,
      stock: 130,
    },
    // SEMILLAS - Hierbas
    {
      name: 'Albahaca',
      slug: 'albahaca',
      category: 'semilla',
      subcategory: 'hierba',
      description: 'Albahaca aromática, esencial en la cocina italiana y mexicana.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [2, 3, 4, 8, 9],
      harvestMonths: [5, 6, 7, 10],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'maceta_pequeña',
      germinationRate: 85,
      daysToGerminate: 10,
      daysToHarvest: 40,
      weightOptions: [
        { g: 20, price: 22, stock: 120 },
        { g: 100, price: 85, stock: 55 },
      ],
      images: ['https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400'],
      price: 22,
      stock: 175,
    },
    {
      name: 'Cilantro',
      slug: 'cilantro',
      category: 'semilla',
      subcategory: 'hierba',
      description: 'Cilantro fresco para cocina mexicana. Cultivo rápido.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [1, 2, 3, 9, 10, 11],
      harvestMonths: [3, 4, 5, 11, 12],
      waterNeeds: 2,
      sunNeeds: 2,
      careLevel: 1,
      spaceNeeded: 'maceta_pequeña',
      germinationRate: 88,
      daysToGerminate: 7,
      daysToHarvest: 45,
      weightOptions: [
        { g: 30, price: 20, stock: 150 },
        { g: 100, price: 55, stock: 70 },
      ],
      images: ['https://images.unsplash.com/photo-1526346698789-22fd84314424?w=400'],
      price: 20,
      stock: 220,
    },
    {
      name: 'Epazote',
      slug: 'epazote',
      category: 'semilla',
      subcategory: 'hierba',
      description: 'Hierba tradicional mexicana, indispensable para frijoles.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'seca_calida', 'templada'],
      sowMonths: [3, 4, 5],
      harvestMonths: [6, 7, 8],
      waterNeeds: 1,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'maceta_pequeña',
      germinationRate: 80,
      daysToGerminate: 14,
      daysToHarvest: 50,
      weightOptions: [
        { g: 20, price: 18, stock: 60 },
      ],
      images: ['https://images.unsplash.com/photo-1515023115689-589c33041d3c?w=400'],
      price: 18,
      stock: 60,
    },
    {
      name: 'Hierbabuena',
      slug: 'hierbabuena',
      category: 'semilla',
      subcategory: 'hierba',
      description: 'Hierbabuena fresca para tés y cócteles.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [2, 3, 4, 9, 10],
      harvestMonths: [5, 6, 10, 11],
      waterNeeds: 3,
      sunNeeds: 2,
      careLevel: 1,
      spaceNeeded: 'maceta_pequeña',
      germinationRate: 75,
      daysToGerminate: 14,
      daysToHarvest: 60,
      weightOptions: [
        { g: 20, price: 22, stock: 80 },
      ],
      images: ['https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=400'],
      price: 22,
      stock: 80,
    },
    {
      name: 'Orégano',
      slug: 'oregano',
      category: 'semilla',
      subcategory: 'hierba',
      description: 'Orégano mediterráneo, aromático y resistente.',
      isOrganic: false,
      climateZones: ['templada', 'fria_montana'],
      sowMonths: [3, 4],
      harvestMonths: [6, 7, 8],
      waterNeeds: 1,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'maceta_pequeña',
      germinationRate: 70,
      daysToGerminate: 14,
      daysToHarvest: 90,
      weightOptions: [
        { g: 20, price: 25, stock: 55 },
      ],
      images: ['https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400'],
      price: 25,
      stock: 55,
    },
    // SEMILLAS - Flores
    {
      name: 'Girasol',
      slug: 'girasol',
      category: 'semilla',
      subcategory: 'flor',
      description: 'Girasol brillante que atrae polinizadores. Fácil de cultivar.',
      isOrganic: false,
      climateZones: ['costera_humeda', 'seca_calida', 'templada'],
      sowMonths: [3, 4, 5],
      harvestMonths: [7, 8, 9],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'jardín',
      germinationRate: 92,
      daysToGerminate: 7,
      daysToHarvest: 80,
      weightOptions: [
        { g: 50, price: 28, stock: 70 },
        { g: 200, price: 90, stock: 30 },
      ],
      images: ['https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=400'],
      price: 28,
      stock: 100,
    },
    {
      name: 'Cempasúchil',
      slug: 'cempasuchil',
      category: 'semilla',
      subcategory: 'flor',
      description: 'Flor mexicana tradicional para Día de Muertos. Hermosos colores naranja y amarillo.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [6, 7],
      harvestMonths: [10, 11],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'jardín',
      germinationRate: 88,
      daysToGerminate: 7,
      daysToHarvest: 100,
      weightOptions: [
        { g: 30, price: 25, stock: 90 },
        { g: 100, price: 65, stock: 40 },
      ],
      images: ['https://images.unsplash.com/photo-1606189934846-a527add8a77b?w=400'],
      price: 25,
      stock: 130,
    },
    {
      name: 'Lavanda',
      slug: 'lavanda',
      category: 'semilla',
      subcategory: 'flor',
      description: 'Lavanda aromática, relajante y decorativa.',
      isOrganic: true,
      climateZones: ['templada', 'fria_montana'],
      sowMonths: [1, 2, 3],
      harvestMonths: [6, 7, 8],
      waterNeeds: 1,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'maceta_grande',
      germinationRate: 60,
      daysToGerminate: 21,
      daysToHarvest: 120,
      weightOptions: [
        { g: 20, price: 35, stock: 45 },
      ],
      images: ['https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=400'],
      price: 35,
      stock: 45,
    },
    // TIERRA
    {
      name: 'Tierra Preparada Universal',
      slug: 'tierra-preparada-universal',
      category: 'tierra',
      subcategory: null,
      description: 'Tierra fertilizedada y lista para usar. Mezcla perfecta de turba, perlita y vermiculita.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 5000, price: 120, stock: 40 },
        { g: 20000, price: 380, stock: 15 },
      ],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: 120,
      stock: 55,
    },
    {
      name: 'Tierra para Macetas',
      slug: 'tierra-para-macetas',
      category: 'tierra',
      subcategory: null,
      description: 'Tierra ligera y drenante, ideal para macetas y contenedores.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 5000, price: 135, stock: 35 },
        { g: 20000, price: 420, stock: 12 },
      ],
      images: ['https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400'],
      price: 135,
      stock: 47,
    },
    {
      name: 'Tierra para Huerto',
      slug: 'tierra-para-huerto',
      category: 'tierra',
      subcategory: null,
      description: 'Tierra rica en nutrientes para huertos. Mezcla con composta y abonos orgánicos.',
      isOrganic: true,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 10000, price: 180, stock: 25 },
        { g: 20000, price: 320, stock: 10 },
      ],
      images: ['https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400'],
      price: 180,
      stock: 35,
    },
    {
      name: 'Tierra para Cactus y Suculentas',
      slug: 'tierra-para-cactus',
      category: 'tierra',
      subcategory: null,
      description: 'Mezcla arenosa y drenante para cactus y plantas suculentas.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 2000, price: 85, stock: 30 },
        { g: 5000, price: 180, stock: 15 },
      ],
      images: ['https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400'],
      price: 85,
      stock: 45,
    },
    // COMPOSTA
    {
      name: 'Composta Premium',
      slug: 'composta-premium',
      category: 'composta',
      subcategory: null,
      description: 'Composta 100% orgánica de alta calidad. Mejora la estructura del suelo y aporta nutrientes.',
      isOrganic: true,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 5000, price: 95, stock: 50 },
        { g: 20000, price: 280, stock: 20 },
      ],
      images: ['https://images.unsplash.com/photo-1591886960571-74d43a9e5258?w=400'],
      price: 95,
      stock: 70,
    },
    {
      name: 'Humus de Lombriz',
      slug: 'humus-de-lombriz',
      category: 'composta',
      subcategory: null,
      description: 'Abono orgánico de alta concentración. Ideal para plántulas y plantas delicadas.',
      isOrganic: true,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 2000, price: 75, stock: 40 },
        { g: 10000, price: 280, stock: 15 },
      ],
      images: ['https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400'],
      price: 75,
      stock: 55,
    },
    {
      name: 'Composta para Huerto',
      slug: 'composta-para-huerto',
      category: 'composta',
      subcategory: null,
      description: 'Composta enriquecida con minerales para huertos productivos.',
      isOrganic: true,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 10000, price: 150, stock: 30 },
        { g: 25000, price: 320, stock: 12 },
      ],
      images: ['https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400'],
      price: 150,
      stock: 42,
    },
    {
      name: 'Tierra Negra con Composta',
      slug: 'tierra-negra-composta',
      category: 'composta',
      subcategory: null,
      description: 'Mezcla de tierra negra con composta. Lista para plantar directamente.',
      isOrganic: true,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 15000, price: 160, stock: 25 },
        { g: 30000, price: 280, stock: 8 },
      ],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: 160,
      stock: 33,
    },
    // ACCESORIOS
    {
      name: 'Maceta de Barro #10',
      slug: 'maceta-barro-10',
      category: 'accesorio',
      subcategory: null,
      description: 'Maceta de barro artesanal, ideal para interiores y exteriores.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 1000, price: 85, stock: 30 },
      ],
      images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=400'],
      price: 85,
      stock: 30,
    },
    {
      name: 'Maceta de Plástico #8',
      slug: 'maceta-plastico-8',
      category: 'accesorio',
      subcategory: null,
      description: 'Maceta de plástico resistente con drenaje. Ligera y económica.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 200, price: 35, stock: 60 },
      ],
      images: ['https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400'],
      price: 35,
      stock: 60,
    },
    {
      name: 'Bolsas de Cultivo 10L',
      slug: 'bolsas-cultivo-10l',
      category: 'accesorio',
      subcategory: null,
      description: 'Bolsas de tela geotextil para cultivo.Excelente aireación de raíces.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 100, price: 45, stock: 50 },
      ],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: 45,
      stock: 50,
    },
    {
      name: 'Regadera de Plástico 5L',
      slug: 'regadera-5l',
      category: 'accesorio',
      subcategory: null,
      description: 'Regadera práctica con alcance extendido. Ideal para balcones.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 300, price: 95, stock: 25 },
      ],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: 95,
      stock: 25,
    },
    {
      name: 'Tijeras de Poda',
      slug: 'tijeras-poda',
      category: 'accesorio',
      subcategory: null,
      description: 'Tijeras de poda afiladas con mango ergonómico.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 200, price: 120, stock: 20 },
      ],
      images: ['https://images.unsplash.com/photo-1617576683096-00fc8eecb3af?w=400'],
      price: 120,
      stock: 20,
    },
    {
      name: 'Guantes de Jardinería',
      slug: 'guantes-jardineria',
      category: 'accesorio',
      subcategory: null,
      description: 'Guantes resistentes con protección de nudillos.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 100, price: 65, stock: 35 },
      ],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: 65,
      stock: 35,
    },
    {
      name: 'Rastrillo de Mano',
      slug: 'rastrillo-mano',
      category: 'accesorio',
      subcategory: null,
      description: 'Rastrillo pequeño para airear tierra en macetas.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 200, price: 55, stock: 25 },
      ],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: 55,
      stock: 25,
    },
    {
      name: 'Manguera con Pistola 10m',
      slug: 'manguera-10m',
      category: 'accesorio',
      subcategory: null,
      description: 'Manguera flexible con pistola de riego adjustable.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 1500, price: 280, stock: 10 },
      ],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: 280,
      stock: 10,
    },
    {
      name: 'Semáforo de Riego',
      slug: 'semaforo-riego',
      category: 'accesorio',
      subcategory: null,
      description: 'Medidor de humedad del suelo. Evita exceso o falta de riego.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [
        { g: 100, price: 110, stock: 15 },
      ],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: 110,
      stock: 15,
    },
    {
      name: 'Kit de Semillas para Principiantes',
      slug: 'kit-semillas-principiantes',
      category: 'semilla',
      subcategory: 'hortaliza',
      description: 'Incluye tomate cherry, albahaca, cilantro y lechuga. Todo lo necesario para comenzar.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [1, 2, 3, 4, 8, 9, 10],
      harvestMonths: [4, 5, 6, 10, 11, 12],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'maceta_grande',
      germinationRate: 88,
      daysToGerminate: 10,
      daysToHarvest: 65,
      weightOptions: [
        { g: 200, price: 150, stock: 40 },
      ],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: 150,
      stock: 40,
    },
  ];

  for (const product of seedProducts) {
    await db.insert(products).values({
      ...product,
      images: product.images as string[] | null,
      weightOptions: product.weightOptions as unknown as typeof products.$inferInsert.weightOptions,
    });
  }

  console.log(`✅ Created ${seedProducts.length} products`);
  console.log('🎉 Seed completed!');
}

seed().catch(console.error);
