import 'dotenv/config';
import { db } from '../client';
import { products } from '../schema/products';

export async function seed(): Promise<void> {
  console.log('🔄 Seeding regional products expansion...');

  // Regional products from Colima (20+ products)
  const regionalProducts = [
    // FRUTAS TROPICALES (Colima Costa)
    {
      name: 'Mango Ataulfo',
      slug: 'mango-ataulfo',
      category: 'semilla',
      subcategory: 'fruta_tropical',
      description: 'Mango Ataulfo de Colima, conocido por su carne fiberless y sabor dulce intenso. Ideal para clima tropical costero.',
      isOrganic: true,
      climateZones: ['costera_humeda'],
      sowMonths: [3, 4, 5],
      harvestMonths: [5, 6, 7, 8],
      waterNeeds: 3,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'campo',
      germinationRate: '75.00',
      daysToGerminate: 21,
      daysToHarvest: 730, // ~2 years to fruit
      weightOptions: [{ g: 50, price: 45, stock: 40 }],
      images: ['https://images.unsplash.com/photo-1553279768-865429fa0078?w=400'],
      price: '45.00',
      stock: 40,
      seoTitle: 'Semillas de Mango Ataulfo Orgánico | Colima',
      seoDescription: 'Semillas de mango Ataulfo de Colima. Cultivo tropical premium.',
    },
    {
      name: 'Mango Kent',
      slug: 'mango-kent',
      category: 'semilla',
      subcategory: 'fruta_tropical',
      description: 'Mango Kent de gran tamaño, pulpa firme y dulce. Excelente para exportacion y consumo local.',
      isOrganic: false,
      climateZones: ['costera_humeda'],
      sowMonths: [3, 4, 5],
      harvestMonths: [6, 7, 8],
      waterNeeds: 3,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'campo',
      germinationRate: '70.00',
      daysToGerminate: 25,
      daysToHarvest: 1095, // ~3 years
      weightOptions: [{ g: 50, price: 48, stock: 35 }],
      images: ['https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400'],
      price: '48.00',
      stock: 35,
    },
    {
      name: 'Mango Manila',
      slug: 'mango-manila',
      category: 'semilla',
      subcategory: 'fruta_tropical',
      description: 'Variedad tradicional mexicana, pequeño y muy dulce. Cultivado en la zona costera de Colima.',
      isOrganic: true,
      climateZones: ['costera_humeda'],
      sowMonths: [4, 5],
      harvestMonths: [7, 8],
      waterNeeds: 3,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'campo',
      germinationRate: '72.00',
      daysToGerminate: 20,
      daysToHarvest: 730,
      weightOptions: [{ g: 50, price: 42, stock: 45 }],
      images: ['https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400'],
      price: '42.00',
      stock: 45,
    },
    {
      name: 'Coco',
      slug: 'coco',
      category: 'semilla',
      subcategory: 'fruta_tropical',
      description: 'Coco de la costa de Manzanillo. Productor de agua fresca y pulpa nutritiva.',
      isOrganic: false,
      climateZones: ['costera_humeda'],
      sowMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      waterNeeds: 3,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'campo',
      germinationRate: '95.00',
      daysToGerminate: 60,
      daysToHarvest: 1095,
      weightOptions: [{ g: 100, price: 65, stock: 30 }],
      images: ['https://images.unsplash.com/photo-1528825871115-3581a5387919?w=400'],
      price: '65.00',
      stock: 30,
    },
    {
      name: 'Guanábana',
      slug: 'guanabana',
      category: 'semilla',
      subcategory: 'fruta_tropical',
      description: 'Guanábana cremosa y aromática. Fruto tropical con propiedades nutricionales destacadas.',
      isOrganic: true,
      climateZones: ['costera_humeda'],
      sowMonths: [3, 4, 5],
      harvestMonths: [7, 8, 9],
      waterNeeds: 3,
      sunNeeds: 2,
      careLevel: 2,
      spaceNeeded: 'campo',
      germinationRate: '80.00',
      daysToGerminate: 30,
      daysToHarvest: 730,
      weightOptions: [{ g: 50, price: 55, stock: 25 }],
      images: ['https://images.unsplash.com/photo-1587132137056-bfbf0166836e?w=400'],
      price: '55.00',
      stock: 25,
    },
    {
      name: 'Noni',
      slug: 'noni',
      category: 'semilla',
      subcategory: 'fruta_tropical',
      description: 'Fruto Noni de propiedades medicinales. Conocido por sus beneficios para la salud en la medicina tradicional.',
      isOrganic: true,
      climateZones: ['costera_humeda'],
      sowMonths: [4, 5, 6],
      harvestMonths: [9, 10, 11],
      waterNeeds: 3,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'campo',
      germinationRate: '60.00',
      daysToGerminate: 45,
      daysToHarvest: 730,
      weightOptions: [{ g: 50, price: 70, stock: 20 }],
      images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400'],
      price: '70.00',
      stock: 20,
    },
    {
      name: 'Papaya',
      slug: 'papaya',
      category: 'semilla',
      subcategory: 'fruta_tropical',
      description: 'Papaya hawaiana de pulpa roja y dulce. Cultivo rápido y productivo en clima tropical.',
      isOrganic: false,
      climateZones: ['costera_humeda', 'seca_calida'],
      sowMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      harvestMonths: [6, 7, 8, 9, 10],
      waterNeeds: 3,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'jardín',
      germinationRate: '88.00',
      daysToGerminate: 14,
      daysToHarvest: 270,
      weightOptions: [{ g: 50, price: 35, stock: 50 }],
      images: ['https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400'],
      price: '35.00',
      stock: 50,
    },
    // FRUTAS DE SIERRA
    {
      name: 'Café de Altura',
      slug: 'cafe-altura-colima',
      category: 'semilla',
      subcategory: 'fruta_sierra',
      description: 'Café de la Sierra de Manantlán, Colima. Cultivo de altura con perfil de sabor único.',
      isOrganic: true,
      climateZones: ['fria_montana', 'templada'],
      sowMonths: [6, 7, 8],
      harvestMonths: [11, 12, 1],
      waterNeeds: 2,
      sunNeeds: 2,
      careLevel: 3,
      spaceNeeded: 'campo',
      germinationRate: '65.00',
      daysToGerminate: 60,
      daysToHarvest: 1095,
      weightOptions: [{ g: 100, price: 120, stock: 30 }],
      images: ['https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400'],
      price: '120.00',
      stock: 30,
    },
    {
      name: 'Plátano Macho',
      slug: 'platano-macho',
      category: 'semilla',
      subcategory: 'fruta_sierra',
      description: 'Plátano macho para cocción, ingrediente esencial en la cocina mexicana. Muy productivo.',
      isOrganic: false,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [3, 4, 5, 6],
      harvestMonths: [9, 10, 11],
      waterNeeds: 3,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'campo',
      germinationRate: '90.00',
      daysToGerminate: 21,
      daysToHarvest: 365,
      weightOptions: [{ g: 50, price: 40, stock: 45 }],
      images: ['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400'],
      price: '40.00',
      stock: 45,
    },
    {
      name: 'Chirimoya',
      slug: 'chirimoya',
      category: 'semilla',
      subcategory: 'fruta_sierra',
      description: 'Chirimoya de la Sierra de Manantlán. Fruta dulce y cremosa, considerado manjar en Colima.',
      isOrganic: true,
      climateZones: ['templada', 'fria_montana'],
      sowMonths: [3, 4],
      harvestMonths: [10, 11, 12],
      waterNeeds: 2,
      sunNeeds: 2,
      careLevel: 3,
      spaceNeeded: 'campo',
      germinationRate: '50.00',
      daysToGerminate: 45,
      daysToHarvest: 1460,
      weightOptions: [{ g: 50, price: 80, stock: 15 }],
      images: ['https://images.unsplash.com/photo-1580920342480-1c6abeb78ab8?w=400'],
      price: '80.00',
      stock: 15,
    },
    {
      name: 'Mamey Rojo',
      slug: 'mamey-rojo',
      category: 'semilla',
      subcategory: 'fruta_sierra',
      description: 'Mamey rojo con pulpa anaranjada intensa. Fruta tropical de sabor único, ideal para batsidos.',
      isOrganic: false,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [4, 5],
      harvestMonths: [8, 9, 10],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'campo',
      germinationRate: '75.00',
      daysToGerminate: 30,
      daysToHarvest: 730,
      weightOptions: [{ g: 50, price: 55, stock: 35 }],
      images: ['https://images.unsplash.com/photo-1546549032-9571cd6b27df?w=400'],
      price: '55.00',
      stock: 35,
    },
    {
      name: 'Zapote Negro',
      slug: 'zapote-negro',
      category: 'semilla',
      subcategory: 'fruta_sierra',
      description: 'Zapote negro de la Sierra de Colima. Fruta exótica de sabor único y propiedades nutritivas.',
      isOrganic: true,
      climateZones: ['templada'],
      sowMonths: [4, 5],
      harvestMonths: [9, 10],
      waterNeeds: 2,
      sunNeeds: 2,
      careLevel: 3,
      spaceNeeded: 'campo',
      germinationRate: '55.00',
      daysToGerminate: 45,
      daysToHarvest: 1460,
      weightOptions: [{ g: 50, price: 65, stock: 20 }],
      images: ['https://images.unsplash.com/photo-1580920342480-1c6abeb78ab8?w=400'],
      price: '65.00',
      stock: 20,
    },
    {
      name: 'Níspero',
      slug: 'nispero',
      category: 'semilla',
      subcategory: 'fruta_sierra',
      description: 'Níspero de origen asiático adaptado a Colima. Fruto dulce y astringente, rico en fibra.',
      isOrganic: false,
      climateZones: ['templada'],
      sowMonths: [3, 4],
      harvestMonths: [5, 6],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'jardín',
      germinationRate: '70.00',
      daysToGerminate: 30,
      daysToHarvest: 730,
      weightOptions: [{ g: 50, price: 50, stock: 30 }],
      images: ['https://images.unsplash.com/photo-1568702846914-96b305d2ebb1?w=400'],
      price: '50.00',
      stock: 30,
    },
    {
      name: 'Tamarindo',
      slug: 'tamarindo',
      category: 'semilla',
      subcategory: 'fruta_sierra',
      description: 'Tamarindo de Colima. Fruta ácida perfecta para dulces, aguas y salsas.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'seca_calida', 'templada'],
      sowMonths: [5, 6],
      harvestMonths: [2, 3, 4],
      waterNeeds: 1,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'campo',
      germinationRate: '85.00',
      daysToGerminate: 21,
      daysToHarvest: 1095,
      weightOptions: [{ g: 100, price: 45, stock: 40 }],
      images: ['https://images.unsplash.com/photo-1596451190630-186aff535bf2?w=400'],
      price: '45.00',
      stock: 40,
    },
    {
      name: 'Marañón',
      slug: 'marañon',
      category: 'semilla',
      subcategory: 'fruta_sierra',
      description: 'Marañón o merey, produce la nuez de marañón. Fruto tropical con sabor unique.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [4, 5],
      harvestMonths: [8, 9],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 2,
      spaceNeeded: 'campo',
      germinationRate: '72.00',
      daysToGerminate: 25,
      daysToHarvest: 1095,
      weightOptions: [{ g: 50, price: 60, stock: 25 }],
      images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400'],
      price: '60.00',
      stock: 25,
    },
    {
      name: 'Moringa',
      slug: 'moringa',
      category: 'semilla',
      subcategory: 'fruta_sierra',
      description: 'Moringa oleifera, superalimento con alto valor nutricional. Hojas comestibles y semillas medicinales.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'seca_calida', 'templada'],
      sowMonths: [3, 4, 5, 6],
      harvestMonths: [6, 7, 8, 9, 10],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'jardín',
      germinationRate: '80.00',
      daysToGerminate: 10,
      daysToHarvest: 365,
      weightOptions: [{ g: 50, price: 38, stock: 55 }],
      images: ['https://images.unsplash.com/photo-1596097635090-5979c4a4a3c0?w=400'],
      price: '38.00',
      stock: 55,
    },
    {
      name: 'Jamaica (Flor)',
      slug: 'jamaica-flor',
      category: 'semilla',
      subcategory: 'flor',
      description: 'Flor de Jamaica para tés, aguas frescas y cocina. Cultivo tradicional en Colima.',
      isOrganic: true,
      climateZones: ['costera_humeda', 'templada'],
      sowMonths: [4, 5],
      harvestMonths: [8, 9, 10],
      waterNeeds: 2,
      sunNeeds: 3,
      careLevel: 1,
      spaceNeeded: 'jardín',
      germinationRate: '85.00',
      daysToGerminate: 14,
      daysToHarvest: 180,
      weightOptions: [{ g: 50, price: 35, stock: 60 }],
      images: ['https://images.unsplash.com/photo-1598789377918-2d7a5a34d1e7?w=400'],
      price: '35.00',
      stock: 60,
    },
    // ACCESORIOS ADICIONALES
    {
      name: 'Pala de Mano',
      slug: 'pala-mano',
      category: 'accesorio',
      subcategory: null,
      description: 'Pala de mano resistente para plantar y trasplantar. Mango ergonómico y acero templado.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [{ g: 300, price: 95, stock: 25 }],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: '95.00',
      stock: 25,
    },
    {
      name: 'Azadón Pequeño',
      slug: 'azadon-pequeño',
      category: 'accesorio',
      subcategory: null,
      description: 'Azadón de mano para deshierbar y airear tierra. Ideal para huertos urbanos.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [{ g: 400, price: 110, stock: 20 }],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: '110.00',
      stock: 20,
    },
    {
      name: 'Sprinkler de Jardín',
      slug: 'sprinkler-jardin',
      category: 'accesorio',
      subcategory: null,
      description: 'Aspersor oscilante para riego automático. Cubre hasta 300m2.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [{ g: 500, price: 180, stock: 15 }],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: '180.00',
      stock: 15,
    },
    {
      name: 'Tutores de Bambú',
      slug: 'tutores-bambu',
      category: 'accesorio',
      subcategory: null,
      description: 'Set de 10 tutores de bambú de 60cm. Ideal para sostener plantas trepadoras.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [{ g: 200, price: 75, stock: 40 }],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: '75.00',
      stock: 40,
    },
    {
      name: 'Rociador Manual',
      slug: 'rociador-manual',
      category: 'accesorio',
      subcategory: null,
      description: 'Rociador de presión con capacidad de 1.5L. Boquilla ajustable para diferentes tipos de roció.',
      isOrganic: false,
      climateZones: [],
      sowMonths: [],
      harvestMonths: [],
      waterNeeds: null,
      sunNeeds: null,
      careLevel: null,
      spaceNeeded: null,
      germinationRate: null,
      daysToGerminate: null,
      daysToHarvest: null,
      weightOptions: [{ g: 200, price: 85, stock: 30 }],
      images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400'],
      price: '85.00',
      stock: 30,
    },
  ];

  // Insert regional products
  let insertedCount = 0;
  for (const product of regionalProducts) {
    try {
      await db.insert(products).values({
        ...product,
        images: product.images as string[] | null,
        weightOptions: product.weightOptions as unknown as typeof products.$inferInsert.weightOptions,
      });
      insertedCount++;
    } catch (error) {
      // Skip duplicates (slug conflict)
      if ((error as Error).message?.includes('duplicate') || (error as Error).message?.includes('unique')) {
        console.warn(`⚠️ Product already exists: ${product.slug}`);
      } else {
        throw error;
      }
    }
  }

  console.log(`✅ ${insertedCount} regional products seeded`);
}
