import {
  pgTable,
  uuid,
  text,
  boolean,
  integer,
  decimal,
  jsonb,
  timestamp,
} from 'drizzle-orm/pg-core';

export const products = pgTable('products', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  category: text('category').notNull(),
  subcategory: text('subcategory'),
  description: text('description').notNull(),
  isOrganic: boolean('is_organic').default(false),
  climateZones: text('climate_zones').array(),
  sowMonths: integer('sow_months').array(),
  harvestMonths: integer('harvest_months').array(),
  waterNeeds: integer('water_needs'),
  sunNeeds: integer('sun_needs'),
  careLevel: integer('care_level'),
  spaceNeeded: text('space_needed'),
  germinationRate: decimal('germination_rate', { precision: 5, scale: 2 }),
  daysToGerminate: integer('days_to_germinate'),
  daysToHarvest: integer('days_to_harvest'),
  weightOptions: jsonb('weight_options'),
  images: text('images').array(),
  price: decimal('price', { precision: 10, scale: 2 }).notNull(),
  stock: integer('stock').default(0),
  seoTitle: text('seo_title'),
  seoDescription: text('seo_description'),
  isArchived: boolean('is_archived').default(false),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const categories = pgTable('categories', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  image: text('image'),
  parentId: uuid('parent_id'),
  createdAt: timestamp('created_at').defaultNow(),
});
